// react/src/components/EventComponent.tsx
import { useState } from "react";
import { BalInput, BalText } from "@baloise/design-system-next-components-react";

function EventComponent() {
  const [myName, setMyName] = useState<string | undefined>();

  return (
    <div>
      <BalInput
        placeholder="Tell us your name"
        value={myName}
        onBalInput={(e) => setMyName(e.detail)}
      ></BalInput>
      <BalText>My name is {myName}</BalText>
    </div>
  );
}

export default EventComponent;

// vue/src/components/Event.vue
<script setup lang="ts">
import { ref } from "vue";
import { BalInput, BalText } from "@baloise/design-system-next-components-vue";
import { Events } from "@baloise/design-system-next-components";

const myName = ref<string | undefined>();

function updateName(event: Events.BalInputChange) {
  myName.value = event.detail;
}
</script>

<template>
  <BalInput
    placeholder="Tell us your name"
    :value="myName"
    @balInput="updateName($event)"
  ></BalInput>
  <BalText>My name is {{ myName }}</BalText>
</template>
