// react/src/components/PropertyComponent.tsx
import { useState } from "react";
import type { Props } from "@baloise/design-system-next-components";
import {
  BalButton,
  BalButtonGroup,
} from "@baloise/design-system-next-components-react";

function PropertyComponent() {
  const [myColor] = useState<Props.BalButtonColor>("info");

  return (
    <BalButtonGroup>
      <BalButton color="danger">My danger button</BalButton>
      <BalButton disabled>My disabled button</BalButton>
      <BalButton color={myColor}>My info button</BalButton>
    </BalButtonGroup>
  );
}

export default PropertyComponent;

// vue/src/components/Property.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Props } from "@baloise/design-system-next-components";
import {
  BalButton,
  BalButtonGroup,
} from "@baloise/design-system-next-components-vue";

const myColor = ref<Props.BalButtonColor>("info");
</script>

<template>
  <BalButtonGroup>
    <!-- Statically set property -->
    <BalButton color="danger">My danger button</BalButton>

    <!-- Properties of type boolean do not need a value. -->
    <BalButton disabled>My disabled button</BalButton>

    <!-- Dynamically set property -->
    <BalButton :color="myColor">My info button</BalButton>
  </BalButtonGroup>
</template>
