// vue/src/components/Method.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  ProxyComponent,
  BalSelect,
  BalSelectOption,
  BalButton,
} from "@baloise/design-system-components-vue";
import { Components } from "@baloise/design-system-components";

const mySelect = ref<ProxyComponent<Components.BalSelect>>();

function chooseTennis() {
  mySelect.value?.$el.select("tennis");
}
</script>

<template>
  <BalSelect ref="mySelect" placeholder="Choose your hobby">
    <BalSelectOption label="Tennis" value="tennis">Tennis</BalSelectOption>
    <BalSelectOption label="Soccer" value="soccer">Soccer</BalSelectOption>
    <BalSelectOption label="Other" value="other">Other</BalSelectOption>
  </BalSelect>
  <BalButton class="mt-normal" @click="chooseTennis()">Choose Tennis</BalButton>
</template>

// angular/src/app/method/method.component.ts
import { Component, ViewChild } from '@angular/core';
import type { Components } from '@baloise/design-system-components';
import { ProxyComponent } from '@baloise/design-system-components-angular';

@Component({
  selector: 'app-method',
  templateUrl: './method.component.html',
})
export class MethodComponent {
  @ViewChild('mySelect') mySelect!: ProxyComponent<Components.BalSelect>;

  chooseTennis(): void {
    this.mySelect.el.select('tennis');
  }
}

<bal-select #mySelect placeholder="Choose your hobby">
  <bal-select-option label="Tennis" value="tennis">Tennis</bal-select-option>
  <bal-select-option label="Soccer" value="soccer">Soccer</bal-select-option>
  <bal-select-option label="Other" value="other">Other</bal-select-option>
</bal-select>
<bal-button class="mt-normal" (click)="chooseTennis()">Choose Tennis</bal-button>
