// vue/src/components/Property.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Props } from "@baloise/design-system-next-components";
import {
  BalButton,
  BalButtonGroup,
} from "@baloise/design-system-next-components-vue";

const myColor = ref<Props.BalButtonColor>("info");
</script>

<template>
  <BalButtonGroup>
    <!-- Statically set property -->
    <BalButton color="danger">My danger button</BalButton>

    <!-- Properties of type boolean do not need a value. -->
    <BalButton disabled>My disabled button</BalButton>

    <!-- Dynamically set property -->
    <BalButton :color="myColor">My info button</BalButton>
  </BalButtonGroup>
</template>

// angular/src/app/property/property.component.ts
import { Component } from '@angular/core';
import { Props } from '@baloise/design-system-next-components';

@Component({
  selector: 'app-property',
  templateUrl: './property.component.html',
})
export class PropertyComponent {
  myColor: Props.BalButtonColor = 'info';
}

<bal-button-group>
  <!-- Statically set property -->
  <bal-button color="danger">My danger button</bal-button>

  <!-- Properties of type boolean do not need a value. -->
  <bal-button disabled>My disabled button</bal-button>

  <!-- Dynamically set property -->
  <bal-button [color]="myColor">My info button</bal-button>
</bal-button-group>
