// vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  BalApp,
  BalFooter,
  BalHeading,
  BalNavbar,
  BalNavbarBrand,
  BalLogo,
  BalText,
  BalStage,
  BalStageBody,
  BalStageImage,
  BalCard,
  BalCardTitle,
  BalCardSubtitle,
  BalCardContent,
} from "@baloise/design-system-components-vue";
import {
  onBalConfigChange,
  BalConfigState,
  BalSwissLanguage,
} from "@baloise/design-system-components";
import PropertyComponent from "./components/Property.vue";
import EventComponent from "./components/Event.vue";
import MethodComponent from "./components/Method.vue";

const title = ref("Welcome");

onBalConfigChange((config: BalConfigState) => {
  const language = config.language as BalSwissLanguage;
  switch (language) {
    case "de":
      title.value = "Willkommen";
      break;
    case "it":
      title.value = "Benvenuta";
      break;
    case "fr":
      title.value = "Bienvenue";
      break;
    default:
      title.value = "Welcome";
      break;
  }
});
</script>

<template>
  <BalApp class="has-sticky-footer has-background">
    <header>
      <BalNavbar>
        <BalNavbarBrand>Vue Example</BalNavbarBrand>
      </BalNavbar>
      <BalStage color="green" size="small">
        <BalStageBody>
          <div class="container is-compact">
            <BalHeading space="none" data-testid="welcome-title">{{
              title
            }}</BalHeading>
            <BalHeading space="none" subtitle level="h2">
              To the Baloise Design System
            </BalHeading>
          </div>
        </BalStageBody>
      </BalStage>
    </header>
    <main class="container is-compact">
      <BalCard class="mt-large">
        <BalCardTitle>Property example</BalCardTitle>
        <BalCardSubtitle>
          A little demonstration how to change properties of our components
        </BalCardSubtitle>
        <BalCardContent>
          <PropertyComponent />
        </BalCardContent>
      </BalCard>

      <BalCard class="mt-large">
        <BalCardTitle>Event example</BalCardTitle>
        <BalCardSubtitle>
          A short example how to use the events of our components
        </BalCardSubtitle>
        <BalCardContent>
          <EventComponent />
        </BalCardContent>
      </BalCard>

      <BalCard class="mt-large">
        <BalCardTitle>Method example</BalCardTitle>
        <BalCardSubtitle>
          A tiny use case of how to call the components methods
        </BalCardSubtitle>
        <BalCardContent>
          <MethodComponent />
        </BalCardContent>
      </BalCard>
    </main>
    <BalFooter></BalFooter>
  </BalApp>
</template>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { BalSwissLanguage } from '@baloise/design-system-components';
import {
  onBalConfigChange,
  BalConfigState,
} from '@baloise/design-system-components';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'Welcome';
  language: BalSwissLanguage = 'en';

  constructor() {
    onBalConfigChange((config: BalConfigState) => {
      this.language = config.language as BalSwissLanguage;

      switch (this.language) {
        case 'de':
          this.title = 'Willkommen';
          break;
        case 'it':
          this.title = 'Benvenuta';
          break;
        case 'fr':
          this.title = 'Bienvenue';
          break;
        default:
          this.title = 'Welcome';
          break;
      }
    });
  }
}

<bal-app class="has-sticky-footer">
  <header>
    <bal-navbar>
      <bal-navbar-brand href="/" target="_blank">Demo</bal-navbar-brand>
    </bal-navbar>
    <bal-stage color="green" shape>
      <bal-stage-body>
        <bal-heading data-testid="welcome-title">{{ title }}</bal-heading>
        <bal-heading subtitle level="h2">
          To the Baloise Design System
        </bal-heading>
      </bal-stage-body>
    </bal-stage>
  </header>
  <main class="container">
    <bal-card class="mt-large">
      <bal-card-title>Property example</bal-card-title>
      <bal-card-subtitle>
        A little demonstration how to change properties of our
        components
      </bal-card-subtitle>
      <bal-card-content>
        <app-property></app-property>
      </bal-card-content>
    </bal-card>
    <bal-card class="mt-large">
      <bal-card-title>Event example</bal-card-title>
      <bal-card-subtitle>
        A short example how to use the events of our
        components
      </bal-card-subtitle>
      <bal-card-content>
        <app-event></app-event>
      </bal-card-content>
    </bal-card>
    <bal-card class="mt-large">
      <bal-card-title>Method example</bal-card-title>
      <bal-card-subtitle>
        A tiny use case of how to call the components methods
      </bal-card-subtitle>
      <bal-card-content>
        <app-method></app-method>
      </bal-card-content>
    </bal-card>
    <bal-card class="mt-large">
      <bal-card-title>Tabs example</bal-card-title>
      <bal-card-subtitle>
        A tiny use case of how to call tabs component
      </bal-card-subtitle>
      <bal-card-content>
        <bal-tabs border="true" fullwidth="true" interface="tabs" [value]="navigationModel">
          <bal-tab-item *ngFor="let item of navigationItems" [value]="item.value" [disabled]="item.disabled"
            [label]="item.label">
          </bal-tab-item>
        </bal-tabs>
      </bal-card-content>
    </bal-card>
    <bal-card class="mt-large">
      <bal-card-title>Reactive form</bal-card-title>
      <bal-card-content>
        <app-form-component [form]="form"></app-form-component>
      </bal-card-content>
    </bal-card>
    <bal-card class="mt-large">
      <bal-card-title>Template form</bal-card-title>
      <bal-card-content>
        <bal-input [(ngModel)]="value">
        </bal-input>
        <bal-text>Value is adapted on: {{value}}</bal-text>
      </bal-card-content>
    </bal-card>

    <bal-card class="mt-large">
      <bal-card-title>Modal example</bal-card-title>
      <bal-card-content>
        <bal-button (click)="openModal()">Open Modal</bal-button>
      </bal-card-content>
    </bal-card>

  </main>
  <bal-footer></bal-footer>
</bal-app>
