// vue/src/components/Event.vue
<script setup lang="ts">
import { ref } from "vue";
import { BalInput, BalText } from "@baloise/design-system-components-vue";
import { Events } from "@baloise/design-system-components";

const myName = ref<string | undefined>();

function updateName(event: Events.BalInputChange) {
  myName.value = event.detail;
}
</script>

<template>
  <BalInput
    placeholder="Tell us your name"
    :value="myName"
    @balInput="updateName($event)"
  ></BalInput>
  <BalText>My name is {{ myName }}</BalText>
</template>

// angular/src/app/event/event.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-event',
  templateUrl: './event.component.html',
})
export class EventComponent {
  myName?: string;

  updateName(value: string | undefined) {
    this.myName = value
  }
}

<bal-input
  placeholder="Tell us your name"
  [value]="myName"
  (balInput)="updateName($event.detail)"
></bal-input>
<bal-text>My name is {{ myName }}</bal-text>
