// vue/src/components/Method.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  ProxyComponent,
  BalSelect,
  BalSelectOption,
  BalButton,
} from "@baloise/design-system-next-components-vue";
import { Components } from "@baloise/design-system-next-components";

const mySelect = ref<ProxyComponent<Components.BalSelect>>();

function chooseTennis() {
  mySelect.value?.$el.select("tennis");
}
</script>

<template>
  <BalSelect ref="mySelect" placeholder="Choose your hobby">
    <BalSelectOption label="Tennis" value="tennis">Tennis</BalSelectOption>
    <BalSelectOption label="Soccer" value="soccer">Soccer</BalSelectOption>
    <BalSelectOption label="Other" value="other">Other</BalSelectOption>
  </BalSelect>
  <BalButton class="mt-4" @click="chooseTennis()">Choose Tennis</BalButton>
</template>

// react/src/components/MethodComponent.tsx
import {
  BalSelect,
  BalSelectOption,
  BalButton,
} from "@baloise/design-system-next-components-react";
import { useRef } from "react";

function MethodComponent() {
  const selectRef = useRef<HTMLBalSelectElement>(null);

  function chooseTennis() {
    selectRef.current?.select("tennis");
  }

  return (
    <div>
      <BalSelect ref={selectRef} placeholder="Choose your hobby">
        <BalSelectOption label="Tennis" value="tennis">
          Tennis
        </BalSelectOption>
        <BalSelectOption label="Soccer" value="soccer">
          Soccer
        </BalSelectOption>
        <BalSelectOption label="Other" value="other">
          Other
        </BalSelectOption>
      </BalSelect>
      <BalButton class="mt-4" onClick={() => chooseTennis()}>
        Choose Tennis
      </BalButton>
    </div>
  );
}

export default MethodComponent;
